name: Terraform AWS Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/qa

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_vpc_id: vpc-059e55d37b3cea072
          TF_VAR_subnet_ids: '["subnet-00e1bff7cea8ae526"]'
          TF_VAR_security_group_id: sg-0d5e8320b99b1b132
          TF_VAR_instance_count: 1
          TF_VAR_instance_type: t3.small
          TF_VAR_key_pair_name: mad

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_vpc_id: vpc-059e55d37b3cea072
          TF_VAR_subnet_ids: '["subnet-00e1bff7cea8ae526"]'
          TF_VAR_security_group_id: sg-0d5e8320b99b1b132
          TF_VAR_instance_count: 1
          TF_VAR_instance_type: t3.small
          TF_VAR_key_pair_name: mad